name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt; 
    - name: Test with unittest
      run: |
        python -m unittest
    - name: Is Website vulnerable
      # You may pin to the exact commit or the version.
      # uses: lirantal/is-website-vulnerable@02d7916b29a1fd9d6a9bea0d83960d4288afa1a6
      uses: lirantal/is-website-vulnerable@1.15.10
      with:
        # Website url to scan
        scan-url: https://loov-alpha-g9qzc.ondigitalocean.app/
    - name: Auto Website to GIF
      # You may pin to the exact commit or the version.
      # uses: PabloLec/website-to-gif@627ef54ff9979e63e2b3c41b2b6ed6514adf1188
      uses: PabloLec/website-to-gif@1.0.4
      with:
        # Web page URL to be captured
        url: https://voudoo.me
        # GIF saving path, starts with /, defaults to repo root
